# Site settings
title: Mapbox Locate
email: dev@ocupop.com
description: 'Mapbox’s first event celebrating and exploring the connectedness of the world around us.'
url: "http://mapbox.com/locate"
permalink: /:title

# Google Analytics
analytics_code: 

# Collections
collections:
  speakers:
    output: true
    permalink: /speaker/:path
  sessions:
    output: true
    permalink: /sessions/:path  

# Build settings
safe: false
source: src

exclude:
  - src/assets/_img
  - src/assets/_js
  - src/assets/_scss

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


  # Schedule Settings

tracks:
  1: 'Business Track 1'
  2: 'Business Track 2'
  3: 'Tech Track 1'
  4: 'Tech Track 2'

timeslots:
  d1_slot1: 'Day 1 - 10:15am'
  d1_slot2: 'Day 1 - 11:00am'
  d1_slot3: 'Day 1 - 11:45am'
  d1_slot4: 'Day 1 - 1:30pm'
  d1_slot5: 'Day 1 - 2:15pm'
  d1_slot6: 'Day 1 - 3:00pm'
  d1_slot7: 'Day 1 - 4:30pm'
  d1_slot8: 'Day 1 - 5:15pm'
  d2_slot1: 'Day 2 - 10:15am'
  d2_slot2: 'Day 2 - 11:00am'

stages:
  stage1: 'Stage 1'
  stage2: 'Stage 2'
  stage3: 'Stage 3'
  stage4: 'Stage 4'
